version: '3.8'

services:
  bridging-service:
    build: .
    container_name: bridging-service
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/bridging_db
      - SPRING_REDIS_HOST=redis
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - SPRING_ELASTICSEARCH_URIS=http://elasticsearch:9200
    networks:
      - digimedic-network
    depends_on:
      - postgres
      - redis
      - kafka
      - elasticsearch

  postgres:
    image: postgres:15-alpine
    container_name: bridging-postgres
    environment:
      POSTGRES_DB: bridging_db
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - digimedic-network

  redis:
    image: redis:7-alpine
    container_name: bridging-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - digimedic-network

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    container_name: bridging-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - digimedic-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: bridging-zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - digimedic-network

  elasticsearch:
    image: elasticsearch:8.7.0
    container_name: bridging-elasticsearch
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - digimedic-network

networks:
  digimedic-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
  elasticsearch_data: